controllers:
    resource:
        path: ../src/Licensing/Infrastructure/Entrypoint/Controller/Symfony
        namespace: App\Licensing\Infrastructure\Entrypoint\Controller\Symfony
    type: attribute
