doctrine:
    dbal:
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
                use_savepoints: true
                driver: pdo_pgsql
                replicas:
                    read:
                        url: '%env(resolve:DATABASE_URL_RO)%'
            read_model:
                url: '%env(resolve:DATABASE_URL_RO)%'

        types:
            entity_id: App\Common\Infrastructure\Persistence\Doctrine\Types\EntityIdType
            money: App\Common\Infrastructure\Persistence\Doctrine\Types\MoneyType

    orm:
        auto_generate_proxy_classes: true
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                validate_xml_mapping: true
                mappings:
                    App\Admin\Licensing:
                        type: xml
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Licensing/Infrastructure/Persistence/Doctrine/Mapping'
                        prefix: 'App\Licensing\Domain\Model'
                        alias: App\Licensing
                    App\Admin\Common:
                        type: xml
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Common/Infrastructure/Persistence/Doctrine/Mapping'
                        prefix: 'App\Common\Domain\Model'
                        alias: App\Common
                    App\Common\Infrastructure\EventStore\Doctrine:
                        type: xml
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Common/Infrastructure/EventStore/Doctrine'
                        prefix: 'App\Common\Infrastructure\EventStore\Doctrine'

            read_model:
                connection: read_model
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    App\Admin\Licensing:
                        type: xml
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Licensing/Infrastructure/Persistence/Doctrine/Mapping'
                        prefix: 'App\Licensing\Domain\Model'
                        alias: App\Licensing
                    App\Admin\Common:
                        type: xml
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Common/Infrastructure/Persistence/Doctrine/Mapping'
                        prefix: 'App\Common\Domain\Model'
                        alias: App\Common

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            # dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
