[supervisord]
nodaemon=true

[program:symfony-app1]
command=frankenphp -r /var/www/symfony-admin/public --port=8001
directory=/var/www/symfony-admin
autostart=true
autorestart=true

[program:symfony-app2]
command=frankenphp -r /var/www/symfony-content/public --port=8002
directory=/var/www/symfony-content
autostart=true
autorestart=true

[program:symfony-app3]
command=frankenphp -r /var/www/symfony-campus/public --port=8003
directory=/var/www/symfony-campus
autostart=true
autorestart=true
